name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build, Storybook & Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 4: Build the library
      - name: Build project
        run: pnpm run build

      # Step 5: Build Storybook
      - name: Build Storybook
        run: pnpm run build-storybook

      # Step 6: Deploy Storybook to GitHub Pages
      - name: Deploy Storybook
        run: pnpm run deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
