name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    name: Build, Version, Storybook & Publish
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 4. Build the library
      - name: Build library
        run: pnpm run build

      # 5. Increment version
      - name: Bump version
        run: |
          pnpm version minor --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version [ci skip]"
          git push

      # 6. Build Storybook
      - name: Build Storybook
        run: pnpm run build-storybook

      # 7. Deploy Storybook to GitHub Pages
      - name: Deploy Storybook
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          pnpm run deploy-storybook

      # 8. Publish package to npm
      - name: Publish package
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
